name: ci-test

on:
  push:
    branches:
      - "*"

jobs:
  dummy:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l ${0}

    steps:
      - name: "conda env"
        run: |
          env | sort | grep -i conda
